#gorm:
#  logger-level:
server:
  address: '0.0.0.0:8080'

oss-aliyun:
  endpoint: 'https://oss-cn-hangzhou.aliyuncs.com'
  access-key-id: 'LTAI5tLEnBd7osB5r2mnJ2gc'
  access-key-secret: 'RN49wBV1enOe99UE9MK1gG5F6aHBPn'
  bucket-name: 'illtamer-web-picture'
  base-url: 'public/bytedance/'
  # 公网访问前缀
  public-url: 'https://illtamer-web-picture.oss-cn-hangzhou.aliyuncs.com/public/bytedance/'

database:
  host: 'illtamer.com'
  port: 2436
  username: 'bytedance'
  password: 'Aa123456_'
  db-name: 'bytedance'
  # interpolateParams - 解决多编码下SQL注入问题，对本项目存在负影响，遂关闭
  settings: 'interpolateParams=false&parseTime=true'

redis:
  host: 'localhost'
  port: 6379
  # 为空字符串则不需要密码
  password: ''
  # 使用的数据库编号，0为使用默认数据库
  db-index: 0